version: "3.8"

services:
  mongo-db:
    image: mongo:5.0
    restart: unless-stopped
    expose:
      - "27017"

  xiang-qi:
    build:
      context: .
      dockerfile: Dockerfile
    image: xiang-qi
    container_name: xiang-qi-back
    restart: on-failure
    depends_on:
      - mongo-db
    ports:
      - "80:8080"
    links:
      - mongo-db